name: Build/push docker image
on:
  workflow_dispatch:
  push:
    branches:
#    - main
    - feat/*
    - develop
    tags:
      - v*

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  docker:
    strategy:
      fail-fast: false
      matrix:
        gpu-driver:
        # arm64 cuda, rocm and cpu images are all CPU!
        # there is no accelerated torch/arm64 build at the moment
          - cuda
          - rocm
          - cpu
    runs-on: ubuntu-latest
    name: ${{ matrix.gpu-driver }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        # see https://github.com/docker/metadata-action
        # will push the following tags:
        # :edge
        # :main (+ any other branches enabled in the workflow)
        # :<tag>
        # :1.2.3 (for semver tags)
        # :1.2 (for semver tags)
        # :<sha>
        tags: |

          type=edge,branch=main
          type=ref,event=branch
          type=ref,event=tag
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=sha

          ### FORK-only ###
          type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'develop') }}

        # suffix image tags with gpu type
        # latest is handled through type=raw
        flavor: |
          latest=false
          suffix=-${{ matrix.gpu-driver }},onlatest=true

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # do not login to container registry on PRs
    - if: github.event_name != 'pull_request'
      name: Docker login
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push the image
      uses: docker/build-push-action@v3
      with:
        cache-from: |
          type=gha
        cache-to: |
          type=gha
        context: .
        build-args: |
          GPU_DRIVER=${{ matrix.gpu-driver }}
        file: docker/Dockerfile
        platforms: linux/amd64,linux/arm64
        # do not push the image on PRs
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
